services:
  database:
    image: postgres:18.1-trixie
    volumes:
      - postgres_lifeplus:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  lifeplus:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 --reload panel.wsgi:application --workers 3 --log-level info
    volumes:
      - .:/app  # Mount for live code changes
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:trixie
    ports:
      - "443:443"
    volumes:
    - ./static:/usr/share/nginx/html/static
    - ./media:/usr/share/nginx/html/media
    - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    - /etc/letsencrypt:/etc/letsencrypt   # <-- ADD
    depends_on:
      - web


volumes:
  postgres_lifeplus:
