services:
  db:
    image: postgres:18.1-trixie
    volumes:
      - postgres_lifeplus:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app  # Mount for live code changes
    depends_on:
      - db


  nginx:
    image: nginx:trixie
    ports:
      - "80:80"
    volumes:
    - ./static:/usr/share/nginx/html/static
    - ./media:/usr/share/nginx/html/media
    - ./.docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
